name: Run deteKT

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  detekt_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          arguments: |
            detektAll
            --build-cache
            --continue
            -PgprUser=${{ github.actor }}
            -PgprKey=${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF to Github
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: build/detekt-sarif-reports/detekt-merged.sarif
      - name: Upload SARIF artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: sarif-reports
          path: "**/build/detekt-sarif-reports/"
          retention-days: 1
