name: Run diKTat

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  diktat_check:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: |
            diktatCheck
            mergeDiktatReports
            -Pdetekt.multiplatform.disabled=true
            -Pdiktat.githubActions=true
            --continue
            -PgprUser=${{ github.actor }}
            -PgprKey=${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF report to Github
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: build/reports/diktat/diktat-merged.sarif
      - name: Upload SARIF artifacts
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: sarif-reports
          path: "**/build/reports/diktat"
          retention-days: 1
